### ISSUE TITLE
babel配置是不是有问题

### ISSUE THREAD

**Issue by wangjieCode** [19Qingfeng/pages#2]

**Comment by wangjieCode** [comment]
构建的代码还是es6

**Comment by 19Qingfeng** [comment]
> 构建的代码还是es6

Babel 没有配置polyfill，如果需要的话可以自行添加。

**Comment by wangjieCode** [comment]
> > 构建的代码还是es6
> 
> Babel 没有配置polyfill，如果需要的话可以自行添加。

箭头函数这种都得polyfill么， babel预设理论上有的吧

**Comment by 19Qingfeng** [comment]
> > > 构建的代码还是es6
> > 
> > 
> > Babel 没有配置polyfill，如果需要的话可以自行添加。
> 
> 箭头函数这种都得polyfill么， babel预设理论上有的吧

我测试了下是有问题的，如果babel不生效的话。ts以及react都会无法编译的。具体不生效指的是？
